export const QuesQuestion = [
    {
        question: "What is the capital of France?",
        difficulty: "easy",
        correctAnswer: "Paris",
        wrongAnswers: ["Berlin", "Madrid", "Rome" , "Paris"],
        language: "English",
    },
    {
        question: "भारत की राजधानी क्या है?",
        difficulty: "easy",
        correctAnswer: "नई दिल्ली",
        wrongAnswers: ["मुंबई",  "नई दिल्ली","कोलकाता", "चेन्नई" ],
        language: "Hindi",
    },
    {
        question: "پاکستان کا سب سے بڑا شہر کون سا ہے؟",
        difficulty: "easy",
        correctAnswer: "کراچی",
        wrongAnswers: ["لاہور", "اسلام آباد", "کراچی" , "کوئٹہ" ],
        language: "Urdu",
    },
    {
        question: "ما هي عاصمة المملكة العربية السعودية؟",
        difficulty: "easy",
        correctAnswer: "الرياض",
        wrongAnswers: ["جدة", "مكة المكرمة", "الدمام" ,  "الرياض"],
        language: "Arabic",
    },
    {
        question: "বাংলাদেশের রাজধানী কোনটি?",
        difficulty: "easy",
        correctAnswer: "ঢাকা",
        wrongAnswers: ["চট্টগ্রাম", "খুলনা", "রাজশাহী" , "ঢাকা"],
        language: "Bengali",
    }, {
        question: "What is the capital of France?",
        difficulty: "easy",
        correctAnswer: "Paris",
        wrongAnswers: ["Paris", "Berlin", "Madrid", "Rome"],
        language: "English",
    },
    {
        question: "پاکستان کا سب سے بڑا شہر کون سا ہے؟",
        difficulty: "easy",
        correctAnswer: "کراچی",
        wrongAnswers: ["لاہور", "اسلام آباد", "کوئٹہ" , "کراچی"],
        language: "Urdu",
    },
    {
        question: "ما هي عاصمة المملكة العربية السعودية؟",
        difficulty: "easy",
        correctAnswer: "الرياض",
        wrongAnswers: ["جدة", "مكة المكرمة", "الدمام" , "الرياض"],
        language: "Arabic",
    },
    {
        question: "বাংলাদেশের রাজধানী কোনটি?",
        difficulty: "easy",
        correctAnswer: "ঢাকা",
        wrongAnswers: ["চট্টগ্রাম", "খুলনা", "রাজশাহী" ,"ঢাকা"],
        language: "Bengali",
    },

    // Questions 6-10
    {
        question: "Who wrote 'One Hundred Years of Solitude'?",
        difficulty: "easy",
        correctAnswer: "Gabriel Garcia Marquez",
        wrongAnswers: ["Isabel Allende", "Pablo Neruda", "Julio Cortázar" ,  "Gabriel Garcia Marquez"],
        language: "English",
    },
    {
        question: "ما هو الجبل الأعلى في العالم؟",
        difficulty: "hard",
        correctAnswer: "إيفرست",
        wrongAnswers: ["كانجشنجو", "ك2", "ماكينلي" , "إيفرست"],
        language: "Arabic",
    },
    {
        question: "বিশ্বের সবচেয়ে বড় মহাসাগর কোনটি?",
        difficulty: "hard",
        correctAnswer: "প্যাসিফিক মহাসাগর",
        wrongAnswers: ["আটলান্টিক মহাসাগর", "ভূমধ্য সাগর", "ভারতীয় মহাসাগর","প্যাসিফিক মহাসাগর"],
        language: "Bengali",
    },
    {
        question: "ما هو اسم الشهرة للكاتب العربي الشهير أحمد شوقي؟",
        difficulty: "hard",
        correctAnswer: "قدس الدنيا",
        wrongAnswers: ["ديوان الجهاد", "السيرة الهلالية", "رسائل الفراعنة","قدس الدنيا"],
        language: "Arabic",
    },
    {
        question: "বিশ্বের সবচেয়ে উচ্চ চূড়ান্ত কোনটি?",
        difficulty: "hard",
        correctAnswer: "মাউন্ট এভারেস্ট",
        wrongAnswers: ["কাঁচাঞ্চঙ্গা", "কে-২", "ম্যাককিনলি","মাউন্ট এভারেস্ট"],
        language: "Bengali",
    }, {
        question: "What is the chemical symbol for gold?",
        difficulty: "hard",
        correctAnswer: "Au",
        wrongAnswers: ["Ag", "Cu", "Fe","Au"],
        language: "English",
    },
    {
        question: "ما هو اسم الشهرة للكاتب الشهير نجيب محفوظ؟",
        difficulty: "hard",
        correctAnswer: "زعيم الرواية العربية",
        wrongAnswers: ["شاعر النيل", "سيد القصة القصيرة", "عميد الأدب العربي","زعيم الرواية العربية"],
        language: "Arabic",
    },
    {
        question: "বিশ্বের সবচেয়ে বড় মহাদেশটি কোনটি?",
        difficulty: "easy",
        correctAnswer: "এশিয়া",
        wrongAnswers: ["উত্তর আমেরিকা", "আফ্রিকা", "ইউরোপ","এশিয়া"],
        language: "Bengali",
    },
    {
        question: "ہمسفر اعلیٰ کون ہیں؟",
        difficulty: "easy",
        correctAnswer: "جاویدان خان",
        wrongAnswers: ["سفیروں کا سفیر", "خزانہ دار", "بہتترین راہنماؤں کا راہنما","جاویدان خان"],
        language: "Urdu",
    },
    {
        question: "Who is known as the 'Father of the Nation' in India?",
        difficulty: "easy",
        correctAnswer: "Mahatma Gandhi",
        wrongAnswers: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Sardar Patel","Mahatma Gandhi"],
        language: "English",
    }, {
        question: "من هو أول رئيس لجمهورية مصر العربية؟",
        difficulty: "hard",
        correctAnswer: "محمد نجيب",
        wrongAnswers: ["جمال عبد الناصر", "أنور السادات", "حسني مبارك","محمد نجيب"],
        language: "Arabic",
    },
    {
        question: "বিশ্ব স্বাস্থ্য দিবস কখন পালন করা হয়?",
        difficulty: "easy",
        correctAnswer: "এপ্রিল 7",
        wrongAnswers: ["মার্চ 8", "জুন 12", "অক্টোবর 24","এপ্রিল 7"],
        language: "Bengali",
    },
    {
        question: "ما هو اسم النهر الذي يمر بمدينة بغداد؟",
        difficulty: "easy",
        correctAnswer: "دجلة",
        wrongAnswers: ["الفرات", "النيل", "اليانغتسي", "دجلة"],
        language: "Arabic",
    },
    {
        question: "भारतीय चित्रकला के प्रसिद्ध कलाकार कौन हैं?",
        difficulty: "hard",
        correctAnswer: "म.फसीह",
        wrongAnswers: ["नंदलाल बोस", "मीरा मुक्ता", "अनुपम सुखलानी","म.फसीह"],
        language: "Hindi",
    },
    {
        question: "ہندوستان کے کس شہر میں قتل عام 1919 کا واقعہ ہوا؟",
        difficulty: "hard",
        correctAnswer: "آمرتسر",
        wrongAnswers: ["لاہور", "کراچی", "دہلی","آمرتسر"],
        language: "Urdu",
    }, {
        question: "Which planet is known as the 'Red Planet'?",
        difficulty: "easy",
        correctAnswer: "Mars",
        wrongAnswers: ["Venus", "Jupiter", "Saturn","Mars"],
        language: "English",
    },
    {
        question: "جمہوریہ پاکستان کب قائم ہوئی؟",
        difficulty: "easy",
        correctAnswer: "14 اگست 1947",
        wrongAnswers: ["23 مارچ 1956", "16 دسمبر 1971", "3 مئی 2002","14 اگست 1947"],
        language: "Urdu",
    },
    {
        question: "বিশ্ববিদ্যালয়ের শহরটি কোনটি?",
        difficulty: "hard",
        correctAnswer: "প্রিন্সটন",
        wrongAnswers: ["হ্যার্ভার্ড", "ক্যামব্রিজ", "মিট","প্রিন্সটন"],
        language: "Bengali",
    },
    {
        question: "من الشاعر العربي الذي يعرف بـ 'شاعر الحب'؟",
        difficulty: "hard",
        correctAnswer: "مجنون الرومي",
        wrongAnswers: ["المتنبي", "أبو نواس", "أحمد شوقي","مجنون الرومي"],
        language: "Arabic",
    },
    {
        question: "बाल्यकाल में भगवान बुद्ध का नाम क्या था?",
        difficulty: "easy",
        correctAnswer: "सिद्धार्थ",
        wrongAnswers: ["अशोक", "सुमित्रा", "राहुल","सिद्धार्थ"],
        language: "Hindi",
    }, {
        question: "Who is the famous Egyptian singer known as the 'Voice of Egypt'?",
        difficulty: "hard",
        correctAnswer: "Umm Kulthum",
        wrongAnswers: ["Amr Diab", "Fairuz", "Mohammed Abdo","Umm Kulthum"],
        language: "English",
    },
    {
        question: "বাংলাদেশের স্বাধীনতা প্রাপ্তির জন্য কোন সালে মুক্তিযুদ্ধ শুরু হয়েছিল?",
        difficulty: "hard",
        correctAnswer: "1971",
        wrongAnswers: ["1965", "1980", "1990","1971"],
        language: "Bengali",
    },
    {
        question: "من هو مؤلف كتاب 'ألف ليلة وليلة'؟",
        difficulty: "easy",
        correctAnswer: "غير معروف",
        wrongAnswers: ["ابن سينا", "الخوارزمي", "الرازي","غير معروف"],
        language: "Arabic",
    },
    {
        question: "मोहनजोदड़ो किस देश में स्थित है?",
        difficulty: "easy",
        correctAnswer: "पाकिस्तान",
        wrongAnswers: ["भारत", "नेपाल", "बांग्लादेश","पाकिस्तान"],
        language: "Hindi",
    },
    {
        question: "Which English poet wrote 'To be or not to be'?",
        difficulty: "easy",
        correctAnswer: "William Shakespeare",
        wrongAnswers: ["John Keats", "Emily Dickinson", "Robert Frost","William Shakespeare"],
        language: "English",
    }, {
        question: "کوہ ہما ہم سائز رینج کہاں ہے؟",
        difficulty: "hard",
        correctAnswer: "پاکستان",
        wrongAnswers: ["نپال", "ہندوستان", "بھوٹان","پاکستان"],
        language: "Urdu",
    },
    {
        question: "মহাভারত গ্রন্থটির লেখক কে?",
        difficulty: "easy",
        correctAnswer: "বেদব্যাস",
        wrongAnswers: ["বালকৃষ্ণ", "রামায়ণকারণ্য", "মহাভারতবাচান","বেদব্যাস"],
        language: "Bengali",
    },
    {
        question: "ما هو اسم أكبر نهر في العالم؟",
        difficulty: "easy",
        correctAnswer: "الأمازون",
        wrongAnswers: ["النيل", "الميسيسيبي", "اليانغتسي","الأمازون"],
        language: "Arabic",
    },
    {
        question: "सार्वजनिक अच्छूति के समर्थन में किसने आंध्र प्रदेश में 'सत्याग्रह शाला' बनाई थी?",
        difficulty: "hard",
        correctAnswer: "बी.आर. आम्बेडकर",
        wrongAnswers: ["गांधी जी", "बी.आर. आम्बेडकर","जवाहरलाल नेहरू", "सरदार पटेल"],
        language: "Hindi",
    },
    {
        question: "Which famous Egyptian queen is known for her association with Julius Caesar and Mark Antony?",
        difficulty: "easy",
        correctAnswer: "Cleopatra",
        wrongAnswers: ["Cleopatra","Nefertiti", "Hatshepsut", "Isis"],
        language: "English",
    }, {
        question: "من هو مؤلف رواية 'ألف ليلة وليلة'؟",
        difficulty: "hard",
        correctAnswer: "غير معروف",
        wrongAnswers: ["غير معروف" ,"نجيب محفوظ", "طه حسين", "نزار قباني"],
        language: "Arabic",
    },
    {
        question: "বাংলাদেশের প্রথম প্রধানমন্ত্রী কে?",
        difficulty: "easy",
        correctAnswer: "তাজউদ্দিন আহমদ",
        wrongAnswers: ["শেখ মুজিবুর রহমান", "খন্দকার মুশতাক আহমদ","তাজউদ্দিন আহমদ", "মোতিউর রহমান"],
        language: "Bengali",
    },
    {
        question: "What is the holiest city in Islam?",
        difficulty: "easy",
        correctAnswer: "Mecca",
        wrongAnswers: ["Medina","Mecca", "Jerusalem", "Cairo"],
        language: "English",
    },
    {
        question: "भारतीय राजनीतिक विचारक एवं शिक्षाविद कौन थे?",
        difficulty: "hard",
        correctAnswer: "डॉ. राधाकृष्णन",
        wrongAnswers: ["पंडित जवाहरलाल नेहरू", "श्यामा प्रसाद मुखर्जी", "बी.आर. आम्बेडकर" ,"डॉ. राधाकृष्णन"],
        language: "Hindi",
    },
    {
        question: "چین کا سب سے بڑا شہر کون سا ہے؟",
        difficulty: "easy",
        correctAnswer: "بیجنگ",
        wrongAnswers: ["شانگھائی", "بیجنگ" , "ہانگ کانگ", "گوانگژو"],
        language: "Urdu",
    }, {
        question: "Who is the famous Urdu poet known for his work 'Lab Pe Aati Hai Dua Ban Ke Tamanna Meri'?",
        difficulty: "easy",
        correctAnswer: "Allama Iqbal",
        wrongAnswers: ["Mirza Ghalib", "Faiz Ahmed Faiz","Allama Iqbal", "Ahmed Faraz"],
        language: "Urdu",
    },
    {
        question: "বাংলাদেশের জনসংখ্যা কত?",
        difficulty: "easy",
        correctAnswer: "১৬ কোটি (160 million)",
        wrongAnswers: ["১৬ কোটি (160 million)","১২ কোটি", "২০ কোটি", "২৫ কোটি"],
        language: "Bengali",
    },
    {
        question: "ما هو اسم المدينة المقدسة في الهندوسية؟",
        difficulty: "easy",
        correctAnswer: "فاراناسي",
        wrongAnswers: ["هاريدوار", "فاراناسي","أيوديا", "كوروكشيترا"],
        language: "Arabic",
    },
    {
        question: "Which mountain range separates Europe from Asia?",
        difficulty: "easy",
        correctAnswer: "Ural Mountains",
        wrongAnswers: ["Himalayas", "Andes", "Rocky Mountains", "Ural Mountains"],
        language: "English",
    },
    {
        question: "सच्चिदानंद सिन्हा ने किसे 'दो महाद्वीपों का समर्थन' कहा?",
        difficulty: "hard",
        correctAnswer: "बिरबल सहनी",
        wrongAnswers: ["जवाहरलाल नेहरू", "बिरबल सहनी","चन्द्रशेखर आज़ाद", "सरदार पटेल"],
        language: "Hindi",
    }, {
        question: "ما هو اسم الأمير الذي تحول إلى البوذية وأسس الإمبراطورية المورية؟",
        difficulty: "hard",
        correctAnswer: "أشوكا",
        wrongAnswers: ["شانكارا", "شوجا", "جمالا","أشوكا",],
        language: "Arabic",
    },
    {
        question: "মহাকাব্য 'রামায়ণ' রচনা করেছিলেন কে?",
        difficulty: "easy",
        correctAnswer: "বালকৃষ্ণ",
        wrongAnswers: ["বানভট্ট", "বালকৃষ্ণ","ভাসকর", "কালিদাস"],
        language: "Bengali",
    },
    {
        question: "Which desert is the largest hot desert in the world?",
        difficulty: "easy",
        correctAnswer: "Sahara Desert",
        wrongAnswers: ["Sahara Desert","Arabian Desert", "Gobi Desert", "Karakum Desert"],
        language: "English",
    },
    // {
    //     question: "ہندوستان کے کس ریاست کو 'ہندी ہیروز' کہا جاتا ہے؟",
    //     difficulty: "easy",
    //     correctAnswer: "हरियाणा",
    //     wrongAnswers: ["पंजाब", "राजस्थान", "उत्तर प्रदेश"],
    //     language: "Hindi",
    // },
    {
        question: "Who is the famous Arab explorer known for his travels and exploration of the Silk Road?",
        difficulty: "easy",
        correctAnswer: "Ibn Battuta",
        wrongAnswers: ["Ibn Khaldun", "Ibn Battuta","Al-Farabi", "Al-Idrisi"],
        language: "English",
    },
] 